Update patch set 3
Patch Set 3:

unrelated:

Wikibase\Lexeme\Tests\MediaWiki\Specials\HTMLForm\LemmaLanguageFieldTest::testOptionsAreBuildFromLanguagesAndFormatted
PHPUnit_Framework_MockObject_RuntimeException: The provided class "Mock_LemmaLanguageField_e2a69a6d" does not exist

Patch-set: 3
Reviewer: Krinkle <34@e9e9afe9-4712-486d-8885-f54b72dd1951>