Update patch set 1
Patch Set 1: Fails

There were 9 errors:

1) Wikibase\Test\PropertyTest::testNewDataValue with data set #0 (Wikibase\Property, DataValues\StringValue)
MWException: $numericId needs to be an integer

/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:125
/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:274
/home/john/Workspace/DataValues/DataValues/includes/DataValueFactory.php:101
/home/john/Workspace/Wikibase/lib/includes/property/Property.php:166
/home/john/Workspace/Wikibase/lib/tests/phpunit/property/PropertyTest.php:152
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

2) Wikibase\Test\PropertyTest::testNewDataValue with data set #1 (Wikibase\Property, DataValues\StringValue)
MWException: $numericId needs to be an integer

/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:125
/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:274
/home/john/Workspace/DataValues/DataValues/includes/DataValueFactory.php:101
/home/john/Workspace/Wikibase/lib/includes/property/Property.php:166
/home/john/Workspace/Wikibase/lib/tests/phpunit/property/PropertyTest.php:152
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

3) Wikibase\Test\PropertyTest::testNewDataValue with data set #2 (Wikibase\Property, DataValues\StringValue)
MWException: $numericId needs to be an integer

/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:125
/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:274
/home/john/Workspace/DataValues/DataValues/includes/DataValueFactory.php:101
/home/john/Workspace/Wikibase/lib/includes/property/Property.php:166
/home/john/Workspace/Wikibase/lib/tests/phpunit/property/PropertyTest.php:152
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

4) Wikibase\Test\PropertyValueSnakTest::testNewFromPropertyValue with data set #0 (Wikibase\Property, DataValues\StringValue)
MWException: $numericId needs to be an integer

/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:125
/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:274
/home/john/Workspace/DataValues/DataValues/includes/DataValueFactory.php:101
/home/john/Workspace/Wikibase/lib/includes/property/Property.php:166
/home/john/Workspace/Wikibase/lib/includes/snak/PropertyValueSnak.php:151
/home/john/Workspace/Wikibase/lib/tests/phpunit/snak/PropertyValueSnakTest.php:110
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

5) Wikibase\Test\PropertyValueSnakTest::testNewFromPropertyValue with data set #1 (Wikibase\Property, DataValues\StringValue)
MWException: $numericId needs to be an integer

/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:125
/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:274
/home/john/Workspace/DataValues/DataValues/includes/DataValueFactory.php:101
/home/john/Workspace/Wikibase/lib/includes/property/Property.php:166
/home/john/Workspace/Wikibase/lib/includes/snak/PropertyValueSnak.php:151
/home/john/Workspace/Wikibase/lib/tests/phpunit/snak/PropertyValueSnakTest.php:110
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

6) Wikibase\Test\PropertyValueSnakTest::testNewFromPropertyValue with data set #2 (Wikibase\Property, DataValues\StringValue)
MWException: $numericId needs to be an integer

/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:125
/home/john/Workspace/Wikibase/lib/includes/entity/EntityId.php:274
/home/john/Workspace/DataValues/DataValues/includes/DataValueFactory.php:101
/home/john/Workspace/Wikibase/lib/includes/property/Property.php:166
/home/john/Workspace/Wikibase/lib/includes/snak/PropertyValueSnak.php:151
/home/john/Workspace/Wikibase/lib/tests/phpunit/snak/PropertyValueSnakTest.php:110
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

7) Wikibase\Test\ApiCreateClaimTest::testValidRequest
UsageException: Unknown error: "Can only construct StringValue from strings"

/home/john/Workspace/core/includes/api/ApiBase.php:1205
/home/john/Workspace/core/includes/api/ApiBase.php:1387
/home/john/Workspace/Wikibase/repo/includes/api/ApiCreateClaim.php:83
/home/john/Workspace/Wikibase/repo/includes/api/ApiCreateClaim.php:51
/home/john/Workspace/core/includes/api/ApiMain.php:826
/home/john/Workspace/core/includes/api/ApiMain.php:348
/home/john/Workspace/core/tests/phpunit/includes/api/ApiTestCase.php:82
/home/john/Workspace/Wikibase/repo/tests/phpunit/includes/api/ApiCreateClaimTest.php:82
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

8) Wikibase\Test\ApiCreateClaimTest::testMultipleRequests
UsageException: Unknown error: "Can only construct StringValue from strings"

/home/john/Workspace/core/includes/api/ApiBase.php:1205
/home/john/Workspace/core/includes/api/ApiBase.php:1387
/home/john/Workspace/Wikibase/repo/includes/api/ApiCreateClaim.php:83
/home/john/Workspace/Wikibase/repo/includes/api/ApiCreateClaim.php:51
/home/john/Workspace/core/includes/api/ApiMain.php:826
/home/john/Workspace/core/includes/api/ApiMain.php:348
/home/john/Workspace/core/tests/phpunit/includes/api/ApiTestCase.php:82
/home/john/Workspace/Wikibase/repo/tests/phpunit/includes/api/ApiCreateClaimTest.php:233
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

9) Wikibase\Test\ApiSetClaimValueTest::testValidRequests
MWException: Wikibase\SnakObject::newFromType got an array with to few constructor arguments

/home/john/Workspace/Wikibase/lib/includes/snak/SnakObject.php:192
/home/john/Workspace/Wikibase/repo/includes/api/ApiSetClaimValue.php:123
/home/john/Workspace/Wikibase/repo/includes/api/ApiSetClaimValue.php:56
/home/john/Workspace/core/includes/api/ApiMain.php:826
/home/john/Workspace/core/includes/api/ApiMain.php:348
/home/john/Workspace/core/tests/phpunit/includes/api/ApiTestCase.php:82
/home/john/Workspace/Wikibase/repo/tests/phpunit/includes/api/ApiSetClaimValueTest.php:112
/home/john/Workspace/Wikibase/repo/tests/phpunit/includes/api/ApiSetClaimValueTest.php:99
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:61
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47
/home/john/Workspace/core/tests/phpunit/phpunit.php:107

Patch-set: 1