Fix adding multiple qualifiers
Fails with:
"TypeError: claimview._initialQualifiers.hasSnak is not a function"
right now

Change-Id: I0e0d020021c2bdbf4f2e6e211c6b6f9e69d37c90
(cherry picked from commit 62a7a9ff52e34e1f8a217f3e4f46349961e6427f)