Revert "Set 1 hour timeout for entities cached on the client."
There are several errors after merging this changeset. It could be something specific for my setup, but Toby also gets the errors. The actual errors are as the following

There were 5 errors:

1) Wikibase\Test\ChangeHandlerTest::testMergeChanges with data set #2 (array(Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => 1, 'object_id' => 'q1', 'page_id' => 1, 'parent_id' => 0, 'rev_id' => 11, 'revision_id' => 11, 'time' => '20130101010101', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => 2, 'object_id' => 'q1', 'page_id' => 1, 'parent_id' => 11, 'rev_id' => 12, 'revision_id' => 12, 'time' => '20130102020202', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => 1, 'object_id' => 'q1', 'page_id' => 1, 'parent_id' => 12, 'rev_id' => 13, 'revision_id' => 13, 'time' => '20130103030303', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', )), Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => NULL, 'object_id' => 'q1', 'page_id' => 1, 'parent_id' => 0, 'rev_id' => 13, 'revision_id' => 13, 'time' => '20130103030303', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ))
MWException: Failed to load revision 11 of q1

/home/john/Workspace/Wikibase/client/includes/ChangeHandler.php:152
/home/john/Workspace/Wikibase/client/tests/phpunit/includes/ChangeHandlerTest.php:344
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:63
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47

2) Wikibase\Test\ChangeHandlerTest::testCoalesceRuns with data set #2 (array(Wikibase\ItemChange: array ( 'id' => 1101, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1111, 'revision_id' => 1111, 'time' => '20130101010101', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1123, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1112, 'revision_id' => 1112, 'time' => '20130102020202', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', )), array(Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => NULL, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1112, 'revision_id' => 1112, 'time' => '20130102020202', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', )))
Failed to load revision 1111 of q1 [Called from Wikibase\ChangeHandler::coalesceRuns in /home/john/Workspace/Wikibase/client/includes/ChangeHandler.php at line 264]

/home/john/Workspace/core/includes/debug/Debug.php:283
/home/john/Workspace/core/includes/debug/Debug.php:144
/home/john/Workspace/core/includes/GlobalFunctions.php:1103
/home/john/Workspace/Wikibase/client/includes/ChangeHandler.php:264
/home/john/Workspace/Wikibase/client/tests/phpunit/includes/ChangeHandlerTest.php:563
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:63
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47

3) Wikibase\Test\ChangeHandlerTest::testCoalesceRuns with data set #4 (array(Wikibase\ItemChange: array ( 'id' => 1101, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1111, 'revision_id' => 1111, 'time' => '20130101010101', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1123, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1112, 'revision_id' => 1112, 'time' => '20130102020202', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1135, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 0, 'revision_id' => 0, 'time' => '20130105050505', 'type' => 'wikibase-item~remove', 'user_id' => 1, 'user_text' => 'User1', )), array(Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => NULL, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1112, 'revision_id' => 1112, 'time' => '20130102020202', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1135, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 0, 'revision_id' => 0, 'time' => '20130105050505', 'type' => 'wikibase-item~remove', 'user_id' => 1, 'user_text' => 'User1', )))
Failed to load revision 1111 of q1 [Called from Wikibase\ChangeHandler::coalesceRuns in /home/john/Workspace/Wikibase/client/includes/ChangeHandler.php at line 244]

/home/john/Workspace/core/includes/debug/Debug.php:283
/home/john/Workspace/core/includes/debug/Debug.php:144
/home/john/Workspace/core/includes/GlobalFunctions.php:1103
/home/john/Workspace/Wikibase/client/includes/ChangeHandler.php:244
/home/john/Workspace/Wikibase/client/tests/phpunit/includes/ChangeHandlerTest.php:563
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:63
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47

4) Wikibase\Test\ChangeHandlerTest::testCoalesceRuns with data set #6 (array(Wikibase\ItemChange: array ( 'id' => 1101, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1111, 'revision_id' => 1111, 'time' => '20130101010101', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1123, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1112, 'revision_id' => 1112, 'time' => '20130102020202', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1114, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1113, 'revision_id' => 1113, 'time' => '20130101020304', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', )), array(Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => NULL, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1113, 'revision_id' => 1113, 'time' => '20130101020304', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', )))
Failed to load revision 1111 of q1 [Called from Wikibase\ChangeHandler::coalesceRuns in /home/john/Workspace/Wikibase/client/includes/ChangeHandler.php at line 264]

/home/john/Workspace/core/includes/debug/Debug.php:283
/home/john/Workspace/core/includes/debug/Debug.php:144
/home/john/Workspace/core/includes/GlobalFunctions.php:1103
/home/john/Workspace/Wikibase/client/includes/ChangeHandler.php:264
/home/john/Workspace/Wikibase/client/tests/phpunit/includes/ChangeHandlerTest.php:563
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:63
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47

5) Wikibase\Test\ChangeHandlerTest::testCoalesceChanges with data set #4 (array(Wikibase\ItemChange: array ( 'id' => 1101, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1111, 'revision_id' => 1111, 'time' => '20130101010101', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1201, 'object_id' => 'q2', 'parent_id' => 0, 'rev_id' => 1211, 'revision_id' => 1211, 'time' => '20130101010101', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1123, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1112, 'revision_id' => 1112, 'time' => '20130102020202', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1223, 'object_id' => 'q2', 'parent_id' => 0, 'rev_id' => 1212, 'revision_id' => 1212, 'time' => '20130102020202', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1114, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1113, 'revision_id' => 1113, 'time' => '20130101020304', 'type' => 'wikibase-item~update', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1135, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 0, 'revision_id' => 0, 'time' => '20130105050505', 'type' => 'wikibase-item~remove', 'user_id' => 1, 'user_text' => 'User1', )), array(Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => NULL, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 1113, 'revision_id' => 1113, 'time' => '20130101020304', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'bot' => 0, 'comment' => 'wikibase-comment-add', 'id' => NULL, 'object_id' => 'q2', 'parent_id' => 0, 'rev_id' => 1212, 'revision_id' => 1212, 'time' => '20130102020202', 'type' => 'wikibase-item~add', 'user_id' => 1, 'user_text' => 'User1', ), Wikibase\ItemChange: array ( 'id' => 1135, 'object_id' => 'q1', 'parent_id' => 0, 'rev_id' => 0, 'revision_id' => 0, 'time' => '20130105050505', 'type' => 'wikibase-item~remove', 'user_id' => 1, 'user_text' => 'User1', )))
Failed to load revision 1111 of q1 [Called from Wikibase\ChangeHandler::coalesceRuns in /home/john/Workspace/Wikibase/client/includes/ChangeHandler.php at line 244]

/home/john/Workspace/core/includes/debug/Debug.php:283
/home/john/Workspace/core/includes/debug/Debug.php:144
/home/john/Workspace/core/includes/GlobalFunctions.php:1103
/home/john/Workspace/Wikibase/client/includes/ChangeHandler.php:244
/home/john/Workspace/Wikibase/client/includes/ChangeHandler.php:286
/home/john/Workspace/Wikibase/client/tests/phpunit/includes/ChangeHandlerTest.php:620
/home/john/Workspace/core/tests/phpunit/MediaWikiTestCase.php:116
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:63
/home/john/Workspace/core/tests/phpunit/MediaWikiPHPUnitCommand.php:47



This reverts commit 7d294ac5a6cf30579a22acb7a5f7194770a5b1ae

Change-Id: I5325008d19e354033b1448389060e1f3ab4a48c3