Update patch set 3
Patch Set 3: Fails

I did update.php and get 1 remaining error when testing groups Wikibase,Diff,DataValueExtensions:

There was 1 error:

1) Wikibase\Test\TermCacheTest::testSaveTermsOfEntity with data set #0 (Wikibase\TermSqlCache)
MWException: $numericId needs to be an integer

C:\xampp\htdocs\mediawiki\extensions\Wikibase\lib\includes\entity\EntityId.php:85
C:\xampp\htdocs\mediawiki\extensions\Wikibase\lib\includes\entity\EntityObject.php:127
C:\xampp\htdocs\mediawiki\extensions\Wikibase\repo\tests\phpunit\includes\store\TermCacheTest.php:330
C:\xampp\htdocs\mediawiki\tests\phpunit\MediaWikiTestCase.php:87
C:\xampp\htdocs\mediawiki\tests\phpunit\MediaWikiPHPUnitCommand.php:45
C:\xampp\htdocs\mediawiki\tests\phpunit\phpunit.php:107

Patch-set: 3