Update patch set 6
Patch Set 6: -Code-Review

It seems to be a general problem. I'm also getting something similar on current master. Some missing dependency?

wikibase.ValueViewBuilder: global failure
Uncaught TypeError: undefined is not a function

Patch-set: 6