DivergingEntityIdException: Use NormalizedException (1/2)
I had no idea this existed; it makes the code shorter (we no longer have
to construct the parent exception message ourselves) and more consistent
with other normalized exceptions.

The getMessageFromNormalizedMessage() method temporarily needs to be
kept until WikibaseMediaInfo stops using it in change Id234f573c8.

Change-Id: Ic6f324ec4329fd870a9c82dc2fac11381df17f1b