Update patch set 5
Patch Set 5: Verified-1

C:\xampp\htdocs\mediawiki\tests\phpunit>php phpunit.php --group SpecialPage
PHPUnit 3.7.13 by Sebastian Bergmann.

Configuration read from C:\xampp\htdocs\mediawiki\tests\phpunit\suite.xml

E..E.......................................

Time: 4 seconds, Memory: 93.75Mb

There were 2 errors:

1) Wikibase\Test\SpecialCreateItemTest::testExecute
MWException: Title is null

C:\xampp\htdocs\mediawiki\includes\OutputPage.php:1472
C:\xampp\htdocs\mediawiki\includes\OutputPage.php:3675
C:\xampp\htdocs\mediawiki\includes\SpecialPage.php:688
C:\xampp\htdocs\mediawiki\extensions\Wikibase\lib\includes\specials\SpecialWikibasePage.php:79
C:\xampp\htdocs\mediawiki\extensions\Wikibase\repo\includes\specials\SpecialCreateEntity.php:76
C:\xampp\htdocs\mediawiki\extensions\Wikibase\repo\tests\phpunit\includes\specials\SpecialPageTestBase.php:64
C:\xampp\htdocs\mediawiki\extensions\Wikibase\repo\tests\phpunit\includes\specials\SpecialCreateItemTest.php:52
C:\xampp\htdocs\mediawiki\tests\phpunit\MediaWikiTestCase.php:116
C:\xampp\htdocs\mediawiki\tests\phpunit\MediaWikiPHPUnitCommand.php:64
C:\xampp\htdocs\mediawiki\tests\phpunit\MediaWikiPHPUnitCommand.php:48

2) Wikibase\Test\SpecialNewPropertyTest::testExecute
MWException: Title is null

C:\xampp\htdocs\mediawiki\includes\OutputPage.php:1472
C:\xampp\htdocs\mediawiki\includes\OutputPage.php:3675
C:\xampp\htdocs\mediawiki\includes\SpecialPage.php:688
C:\xampp\htdocs\mediawiki\extensions\Wikibase\lib\includes\specials\SpecialWikibasePage.php:79
C:\xampp\htdocs\mediawiki\extensions\Wikibase\repo\includes\specials\SpecialCreateEntity.php:76
C:\xampp\htdocs\mediawiki\extensions\Wikibase\repo\tests\phpunit\includes\specials\SpecialPageTestBase.php:64
C:\xampp\htdocs\mediawiki\extensions\Wikibase\repo\tests\phpunit\includes\specials\SpecialNewPropertyTest.php:51
C:\xampp\htdocs\mediawiki\tests\phpunit\MediaWikiTestCase.php:116
C:\xampp\htdocs\mediawiki\tests\phpunit\MediaWikiPHPUnitCommand.php:64
C:\xampp\htdocs\mediawiki\tests\phpunit\MediaWikiPHPUnitCommand.php:48

FAILURES!
Tests: 43, Assertions: 63, Errors: 2.

Patch-set: 5