Update patch set 15
Patch Set 15: Verified-1

Please test before submitting!

There was 1 error:

1) Wikibase\Test\Api\MergeItemsTest::testMergeRequest with data set "identicalClaimMergeReferences" (array(array(array(array(array('value', '{Prop}', array('imastring', 'string')), 'statement', 'normal', array(array(array(array(array('value', '{Prop}', array('imastring', 'string')))))))))), array(array(array(array(array('value', '{Prop}', array('imastring', 'string')), 'statement', 'normal')))), array(), array(array(array(array(array('value', '{Prop}', array('imastring', 'string')), 'statement', 'normal', array(array(array(array(array('value', '{Prop}', array('imastring', 'string')))))))))))
UsageException: $referenceHash needs to be a string and must not be empty

Patch-set: 15
Reviewer: Daniel Kinzler <128@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=-1