Update patch set 1
Patch Set 1:

Unfortunately, this is not enough. This is what I get after enabling Wikibase content handlers:

1) ContentHandlerSanityTest::testMakeEmptyContent with data set #7 (Wikibase\Repo\Content\ItemHandler Object (...))
RuntimeException: EntityContent was constructed without an EntityId!

While constructor does work, isValid does not. So we have to either remove isValid check or allow it to pass.

Patch-set: 1
Reviewer: Smalyshev <2096@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=0