Update patch set 6
Patch Set 6: There's a problem with this change, please improve

perhaps I have something else wrong with my test wikis, but I cannot edit items and get a bunch of errors:

not exactly sure why and need to investigate this more...

Uncaught TypeError: undefined is not a function wikibase.ui.PropertyEditTool.EditableValue.js:99
Uncaught TypeError: Cannot set property 'Interface' of undefined wikibase.ui.PropertyEditTool.EditableValue.Interface.js:23
Uncaught TypeError: Cannot read property 'Interface' of undefined wikibase.ui.PropertyEditTool.EditableValue.AutocompleteInterface.js:13
Uncaught TypeError: Cannot read property 'AutocompleteInterface' of undefined wikibase.ui.PropertyEditTool.EditableValue.SitePageInterface.js:14
Uncaught TypeError: Cannot read property 'AutocompleteInterface' of undefined wikibase.ui.PropertyEditTool.EditableValue.SiteIdInterface.js:14
Uncaught TypeError: Cannot read property 'Interface' of undefined wikibase.ui.PropertyEditTool.EditableValue.ListInterface.js:13
Uncaught TypeError: Cannot read property 'ListInterface' of undefined wikibase.ui.PropertyEditTool.EditableValue.AliasesInterface.js:13
4
Uncaught TypeError: Cannot read property 'prototype' of undefined wikibase.utilities.js:43
ULS: Unknown language azb. jquery.uls.js:1413
Uncaught TypeError: Cannot call method 'newFromDom' of undefined wikibase.ui.PropertyEditTool.js:297
a

Patch-set: 6