Update patch set 1
Patch Set 1: There's a problem with this change, please improve

Getting an error when running our tests which don't happen on master.
From seeing this I just guess this is because the sites defined in the TestSites.php have the same id now or something.

1) Wikibase\Test\ItemViewTest::testGetHTML with data set #0 (false, '/"wb-sitelinks-empty"/')
DBQueryError: A database error has occurred.  Did you forget to run maintenance/update.php after upgrading?  See: https:

//www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: INSERT  INTO `unittest_site_identifiers` (si_site,si_type,si_key) VALUES ('13','equivalent','enwiktionary')
Function: SiteObject::save
Error: 1062 Duplicate entry 'equivalent-enwiktionary' for key 'site_ids_type' (localhost)

D:\Wikidata\gerrit.wikimedia.org\includes\db\Database.php:932
D:\Wikidata\gerrit.wikimedia.org\includes\db\Database.php:899
D:\Wikidata\gerrit.wikimedia.org\includes\db\Database.php:1655
D:\Wikidata\gerrit.wikimedia.org\extensions\Wikibase\lib\includes\site\SiteObject.php:445
D:\Wikidata\gerrit.wikimedia.org\extensions\Wikibase\lib\tests\phpunit\site\TestSites.php:100
D:\Wikidata\gerrit.wikimedia.org\extensions\Wikibase\repo\tests\phpunit\includes\ItemViewTest.php:55
D:\Wikidata\gerrit.wikimedia.org\tests\phpunit\MediaWikiTestCase.php:85
D:\Wikidata\gerrit.wikimedia.org\tests\phpunit\MediaWikiPHPUnitCommand.php:45
D:\Wikidata\gerrit.wikimedia.org\tests\phpunit\phpunit.php:107

Patch-set: 1