Update patch set 14
Patch Set 14: Verified-1 Code-Review-1

1) Warning
The data provider specified for Wikibase\Test\ChangeOpReferenceTest::testApplyAddNewReference is invalid.
$referenceHash needs to be set

/var/www/daniel/wikidata/tests/phpunit/MediaWikiPHPUnitCommand.php:80
/var/www/daniel/wikidata/tests/phpunit/MediaWikiPHPUnitCommand.php:64

2) ...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1) Wikibase\Test\Api\MergeItemsTest::testMergeRequest with data set "identicalClaimMergeReferences" (array(array(array(array(array('value', '{Prop}', array('imastring', 'string')), 'statement', 'normal', array(array(array(array(array('value', '{Prop}', array('imastring', 'string')))))))))), array(array(array(array(array('value', '{Prop}', array('imastring', 'string')), 'statement', 'normal')))), array(), array(array(array(array(array('value', '{Prop}', array('imastring', 'string')), 'statement', 'normal', array(array(array(array(array('value', '{Prop}', array('imastring', 'string')))))))))))
UsageException: $referenceHash needs to be a string and must not be empty

/var/www/daniel/wikidata/includes/api/ApiBase.php:1324
/var/www/daniel/wikidata/extensions/Wikibase/repo/includes/api/MergeItems.php:71
/var/www/daniel/wikidata/includes/api/ApiMain.php:861
/var/www/daniel/wikidata/includes/api/ApiMain.php:331
/var/www/daniel/wikidata/tests/phpunit/includes/api/ApiTestCase.php:97
/var/www/daniel/wikidata/extensions/Wikibase/repo/tests/phpunit/includes/api/WikibaseApiTestCase.php:85
/var/www/daniel/wikidata/extensions/Wikibase/repo/tests/phpunit/includes/api/MergeItemsTest.php:242
/var/www/daniel/wikidata/tests/phpunit/MediaWikiTestCase.php:123
/var/www/daniel/wikidata/tests/phpunit/MediaWikiPHPUnitCommand.php:80
/var/www/daniel/wikidata/tests/phpunit/MediaWikiPHPUnitCommand.php:64

Patch-set: 14
Label: Verified=-1
Label: Code-Review=-1